---
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - skip: true
archives:
  - format: binary
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  disable: true
  sort: asc
  use: github
# .goreleaser.yaml
release:
  skip_upload: true
  discussion_category_name: announcements
  prerelease: auto
  mode: replace
