---
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - skip: true
archives:
  - format: binary
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: false
  sort: asc
  use: github
# .goreleaser.yaml
release:
  skip_upload: true
  discussion_category_name: announcements
  prerelease: auto
  mode: replace

  # You can add extra pre-existing files to the release.
  # The filename on the release will be the last part of the path (base).
  # If another file with the same name exists, the last one found will be used.
  # These globs can also include templates.
  #
  # Defaults to empty.
  # extra_files:
  #   - glob: ./path/to/file.txt
  #   - glob: ./glob/**/to/**/file/**/*
  #   - glob: ./glob/foo/to/bar/file/foobar/override_from_previous
  #   - glob: ./single_file.txt
  #     name_template: file.txt # note that this only works if glob matches 1 file only
