---
name: changie-trigger-release
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  changelog:
    uses: sheldonhull/github-workflows/.github/workflows/changie-trigger-release.yml@main
    secrets: inherit
