---
name: release
on:
  push:
    #   tags:
    #     - 'v*'
    branches: [main]
    paths: [CHANGELOG.md] # your changelog file if different
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      # https://github.com/magnetikonline/action-golang-cache
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@09043845c4b214830a4ae9eb6f5c61d3d3fd37b0 # renovate: tag=v3
        with:
          go-version-file: go.mod

      - name: mage-tidy
        uses: magefile/mage-action@5f7a9a23cfef763949ca41834b868167adbd1b59 # renovate: tag=v2
        with:
          version: latest
          args: init
      - name: mage-release
        uses: magefile/mage-action@5f7a9a23cfef763949ca41834b868167adbd1b59 # renovate: tag=v2
        with:
          version: latest
          args: release
        env:
          # GitHub sets this automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
