---
name: test
on:
  pull_request:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  pull-requests: read
  contents: read
  checks: write
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: trunk-setup
        run: |
          curl https://get.trunk.io -fsSL | bash -s -- -y
          trunk install
      - name: trunk-test
        run: |
          trunk actions run gotestsum
